name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: 🎨 Linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Formatting
      run: cargo fmt --check
    - name: Clippy
      run: rustup component add clippy && cargo clippy
  tests:
    name: ✅ Tests
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
  perfomance:
    name: ⚡ Performance & 📈 Coverage
    needs:
      - lint
      - tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run performance & coverage tool
      run: cargo run --bin performance --features performance --release
