name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  lint:
    name: 🎨 Linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Formatting
      run: cargo fmt --check
    - name: Clippy
      run: rustup component add clippy
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  tests:
    name: ✅ Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
